name: run-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - name: Build
        run: stack build
